# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autor', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('lang', models.NullBooleanField()),
                ('friends_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('favourites_count', models.IntegerField()),
                ('position_list', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Person_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_person', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('position_list', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at_object', models.DateTimeField()),
                ('text', models.CharField(max_length=150)),
                ('tweet_id', models.IntegerField()),
                ('retweeted', models.BooleanField()),
                ('retweets', models.IntegerField()),
                ('favorite', models.NullBooleanField()),
                ('favorites', models.IntegerField(null=True)),
                ('media', models.NullBooleanField()),
                ('url', models.NullBooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Autores')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.Categorias')),
            ],
        ),
    ]
