# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('author_id', models.IntegerField()),
                ('author', models.CharField(max_length=150)),
                ('tweet_id', models.IntegerField()),
                ('retweeted', models.BooleanField()),
                ('retweets', models.IntegerField()),
            ],
        ),
    ]
