# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='favorites',
            field=models.IntegerField(null=True),
        ),
    ]
