# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweetmodel_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='favorite',
            field=models.NullBooleanField(),
        ),
    ]
